image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-18.04:
  stage: build
  script:
    - cd 18.04
    - docker build --pull -t "$CI_REGISTRY_IMAGE:18.04" .
    - docker push "$CI_REGISTRY_IMAGE:18.04"
  only:
    - master
  environment:
    name: $CI_PIPELINE_SOURCE

build-18.10:
  stage: build
  script:
    - cd 18.10
    - docker build --pull -t "$CI_REGISTRY_IMAGE:18.10" .
    - docker push "$CI_REGISTRY_IMAGE:18.10"
  only:
    - master
  environment:
    name: $CI_PIPELINE_SOURCE

build-18.04-branch:
  stage: build
  script:
    - cd 18.04
    - docker build --pull -t "$CI_REGISTRY_IMAGE:18.04-$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:18.04-$CI_COMMIT_REF_SLUG"
  except:
    - master


build-18.10-branch:
  stage: build
  script:
    - cd 18.10
    - docker build --pull -t "$CI_REGISTRY_IMAGE:18.10-$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:18.10-$CI_COMMIT_REF_SLUG"
  except:
    - master
